osx_image: xcode10.2
language: objective-c
before_install:
  - gem install travis --no-document
script:
  - travis lint .travis.yml --no-interactive
  - xcodebuild clean build -project PaperOnboardingDemo/PaperOnboardingDemo.xcodeproj -scheme PaperOnboardingDemo -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
branches:
only:
  - master
